---
version: '3.9'

services:
  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: selenium-hub
    ports:
      - '4442-4444:4442-4444'

  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_HEIGHT=1200
      - SCREEN_WIDTH=1920
    ports:
      - 5900:5900

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_HEIGHT=1200
      - SCREEN_WIDTH=1920
    ports:
      - 5901:5900
