class PersonalInformationPage:
    # YOUR PERSONAL INFORMATION
    MR_TITLE = "//div[@id='uniform-id_gender1']"
    FIRST_NAME_CUSTOMER = "//input[@id='customer_firstname']"
    LAST_NAME_CUSTOMER = "//input[@id='customer_lastname']"
    EMAIL = "//input[@id='email']"
    PASSWORD = "//input[@id='passwd']"
    # YOUR ADDRESS
    FIRST_NAME = "//input[@id='firstname']"
    LAST_NAME = "//input[@id='lastname']"
    COMPANY = "//input[@id='company']"
    ADDRESS = "//input[@id='address1']"
    CITY = "//input[@id='city']"
    STATE = "//select[@id='id_state']"
    ZIP_CODE = "//input[@id='postcode']"
    COUNTRY = "//select[@id='id_country']"
    ADDITIONAL_INFO = "//textarea[@id='other']"
    HOME_PHONE = "//input[@id='phone']"
    MOBILE_PHONE = "//input[@id='phone_mobile']"
    ALIAS_ADDRESS = "//input[@id='alias']"
    REGISTER = "//button[@id='submitAccount']"
